app.py
from flask import Flask, render_template, url_for, request, g
from app_blueprint import app_blueprint
from config import Config
from dotenv import load_dotenv

# Load environment variables from store.env file
load_dotenv(dotenv_path='store.env')

app = Flask(__name__)  # app itself
app.config.from_object(Config)  # access environment variables

# Register the blueprint
app.register_blueprint(app_blueprint)

# Register teardown function
@app.teardown_appcontext
def teardown_db(exception):
    # Get database connection within g and close (if it exists)
    db = g.pop('db', None)
    if db is not None:
        db.close()

if __name__ == "__main__":
    app.run(debug=True)

app_blueprint.py
from flask import Blueprint, render_template, url_for, request, current_app, jsonify, g
from config import Config
from summon_function import SimulateSummon  # custom summon function
import os
import pymysql.cursors

app_blueprint = Blueprint('app_blueprint', __name__)
MULTI_SUMMON_AMOUNT = 10  # const variable set for multi-summon amount

# Page Formats
@app_blueprint.route('/')  # Home Page
def index():
    return render_template("index.html")

@app_blueprint.route('/summons')  # Summons Page
def summons():
    # Format page based on image/text selected
    choice = request.args.get('choice')

    if choice == 'opt2':
        return render_template("summons.html", choice='opt2')
    else:  # Set option 1 to be default
        return render_template("summons.html", choice='opt1')

# Database Connections Management
def get_db():
    # Establish new database connection within g object
    if 'db' not in g:
        g.db = pymysql.connect(
            host=Config.MYSQL_HOST,
            user=Config.MYSQL_USER,
            password=Config.MYSQL_PASSWORD,
            database=Config.MYSQL_DB,
            cursorclass=pymysql.cursors.DictCursor 
        )
    return g.db

# Summon Functionality
@app_blueprint.route('/summon', methods=['POST'])
def summon():
    # Get table name for specific summom
    data = request.json  # gets data from POST data sent in Jscript
    tableName = data.get('tableName')
    if not tableName:
        return jsonify({'error':'Table name is required'})
    else:

        # Identify number of characters to summon
        multi_summon = data.get('multiSummon', False)  # default to false when not found
        summonAmount = 1  # default set to single summon
        if multi_summon:
            summonAmount = MULTI_SUMMON_AMOUNT 

        # Get database connection & generate characters
        db = get_db()  
        characters = []  # initialise empty list
        for i in range (summonAmount):
            character = SimulateSummon(db, tableName)
            characters.append(character)

        return jsonify ({'characters' : characters})  # convert to JSON response and send back

templates/index.html
{% extends "layout.html" %}  <!--Continue from format of layout.html-->

{% block content %}

<center><h1>Select a Summon to Simulate</h1></center>

<div class="banner-items"> <!--Images placed on left/center of screen-->

    <div class="img-text-container"> <!-- Row-Container with an image alongside the corresponding summon text -->
        <div class="img-left">
            <a href="{{ url_for('app_blueprint.summons', choice='opt1') }}" class="indexLinks">  <!-- send to summons page -->
                <img src="{{ url_for('static', filename='images/core/black asta banner.jpeg') }}" alt="astaBanner">
            </a>
        </div>
        <div class="text-right">
            <a href="{{ url_for('app_blueprint.summons', choice='opt1') }}" class="indexLinks">  <!-- send to summons page -->
                <p class="astaText">&lt;Black&gt; Asta</p>
                <p class="limitedText">Limited Mage Drop Rate Up!</p>
            </a>
        </div>
    </div>

    <div class="img-text-container final-img-text-container">  <!-- Final container must have (final-img-text-container) for footer padding. -->
        <div class="img-left">
            <a href="{{ url_for('app_blueprint.summons', choice='opt2') }}" class="indexLinks">  <!-- send to summons page -->
                <img src="{{url_for('static', filename='images/core/spirit dive yuno banner.jpeg')}}" alt="yunoBanner">
            </a>
        </div>
        <div class="text-right">
            <a href="{{ url_for('app_blueprint.summons', choice='opt2') }}" class="indexLinks">  <!-- send to summons page -->
                <p class="yunoText">&lt;Spirit Dive&gt; Yuno</p>
                <p class="limitedText">Limited Mage Drop Rate Up!</p>
            </a>
        </div>
    </div>

</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BCM Simulator</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
</head>
<body>
    <!-- Acts as a base template for following pages (using jinja2 directive)-->

    {% block nav %}
    <div class="nav-container"> <!-- All navigation container content -->
        <p class="site-title"> BCM Simulator </p>
        <a href="{{url_for('app_blueprint.index')}}" class="nav-link"> Home </a>
        <a href="{{url_for('app_blueprint.summons', choice='opt1')}}" class="nav-link"> Summons </a>
    </div>
    {% endblock nav %}

    <div class="content">
        {% block content %}
            <!-- This block will be overridden by child templates -->
        {% endblock %}
    </div>

    <footer>
        <div class="footer-desc">  <!-- Standard copyright disclaimer in footer content -->
            <p> This site (all assets) nor it's creator is affiliated with or endorsed by; Black Clover Mobile, GArena, Vic Game Studios.  </p>
        </div>
    </footer>

</body>
</html>

templates/summons.html
{% extends "layout.html" %}  <!-- Continue from format of layout.html -->

<!-- Page design is very repetitive, would have to create individual html documents to modularise repeated sub-sections, if more banners were to be added. -->
{% block content %}

    <!-- Initiate script for summons button -->
     <script src="{{url_for('static', filename='scripts/summon.js')}}" defer alt="summon-script"></script>

    <!-- Selected choice is option 2, page formatted for Spirit Dive Yuno -->
    {% if choice == 'opt2' %}
        <center><h1 class="yunoText h1">&lt;Spirit Dive&gt; Yuno</h1></center>
        
       <!-- (Row-Container) Banner image, Summons pulled & butons -->
        <div class="summons-container">
            <div class="summons-img"> <!--Banner Image-->
                <img src="{{url_for('static', filename='images/core/spirit dive yuno banner.jpeg')}}" alt="yunoBanner">
            </div>
    
            <div class="summons-section"> <!-- User's summons -->
                <p class="your-summons-text">Your Summons</p>
                <div class="summons-pulled-container">  <!-- Result of summons -->
                    <p> No Summons to Display </p>
                </div>
                <div class="summons-ticket-container">  <!-- Buttons to Summon -->
                    <div class="left-ticket">
                        <button id="single-summon-btn" data-table="yunoSummon">
                            <img src="{{ url_for('static', filename='images/core/summons one ticket.png') }}" alt="oneTicket">
                        </button>
                    </div>
                    <div class="right-ticket">
                        <button id="multi-summon-btn" data-table="yunoSummon">
                            <img src="{{ url_for('static', filename='images/core/summons ten ticket.png') }}" alt="tenTickets">
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="banner-rates"> <!-- Displayed Rates for summons -->

            <!-- Character Rates -->
            <div class="rate-up-mage">
                <div class="rate-up-text">
                    <p class="left-rate-text"> Rate-UP SSR Mages </p>
                    <p class="right-rate-text orange-text"> 1.00% </p>
                </div>
                <img src="{{ url_for('static', filename='images/characters/char spirit dive yuno.png') }}" alt="charSpiritDiveYuno" class="rate-up-image">
            </div>

            <div class="other-ssr-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SSR </p>
                    <p class="right-rate-text yellow-text"> 1.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other ssr mages.png') }}" alt="otherSSRMages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-sr-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SR </p>
                    <p class="right-rate-text blue-text"> 14.00% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other sr mages.png') }}" alt="otherSRMages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-r-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> R </p>
                    <p class="right-rate-text green-text"> 43.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other r mages.png') }}" alt="otherRMages" class="other-rate-sizes">
                </div>
            </div>

             <!-- Skill Page Rates (also addressed as SPage) -->  
             <div class="rate-up-sPage">
                <div class="rate-up-text">
                    <p class="left-rate-text"> Rate-UP Skill Page </p>
                    <p class="right-rate-text orange-text"> 0.68% </p>
                </div>
                <img src="{{ url_for('static', filename='images/characters/skill page spirit dive yuno.png') }}" alt="SPageSpiritDiveYuno" class="rate-up-image">
            </div>

            <div class="other-ssr-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SSR </p>
                    <p class="right-rate-text yellow-text"> 0.82% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other ssr skill pages.png') }}" alt="otherSSRPages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-sr-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SR </p>
                    <p class="right-rate-text blue-text"> 10.00% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other sr skill pages.png') }}" alt="otherSRPages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-r-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> R </p>
                    <p class="right-rate-text green-text"> 28.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other r skill pages.png') }}" alt="otherRPages" class="other-rate-sizes">
                </div>
            </div>

        </div>

    <!-- Default choice is option 1, page formatted for Black Asta -->
    {% else %}
        <center><h1 class="astaText h1">&lt;Black&gt; Asta</h1></center>

        <!-- (Row-Container) Banner image, Summons pulled & butons -->
        <div class="summons-container">
            <div class="summons-img"> <!--Banner Image-->
                <img src="{{ url_for('static', filename='images/core/black asta banner.jpeg') }}" alt="astaBanner">
            </div>
    
            <div class="summons-section"> <!-- User's summons -->
                <p class="your-summons-text">Your Summons</p>
                <div class="summons-pulled-container">  <!-- Result of summons -->
                    <p> No Summons to Display </p>
                </div>
                <div class="summons-ticket-container">  <!-- Buttons to Summon -->
                    <div class="left-ticket">
                        <button id="single-summon-btn" data-table="astaSummon">
                            <img src="{{ url_for('static', filename='images/core/summons one ticket.png') }}" alt="oneTicket">
                        </button>
                    </div>
                    <div class="right-ticket">
                        <button id="multi-summon-btn" data-table="astaSummon">
                            <img src="{{ url_for('static', filename='images/core/summons ten ticket.png') }}" alt="tenTickets">
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- (Column-Container) Displayed Rates for summons -->
        <div class="banner-rates">

            <!-- Character Rates -->
            <div class="rate-up-mage">
                <div class="rate-up-text">
                    <p class="left-rate-text"> Rate-UP SSR Mages </p>
                    <p class="right-rate-text orange-text"> 1.00% </p>
                </div>
                <img src="{{ url_for('static', filename='images/characters/char black asta.png') }}" alt="charBlackAsta" class="rate-up-image">
            </div>

            <div class="other-ssr-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SSR </p>
                    <p class="right-rate-text yellow-text"> 1.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other ssr mages.png') }}" alt="otherSSRMages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-sr-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SR </p>
                    <p class="right-rate-text blue-text"> 14.00% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other sr mages.png') }}" alt="otherSRMages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-r-mages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> R </p>
                    <p class="right-rate-text green-text"> 43.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other r mages.png') }}" alt="otherRMages" class="other-rate-sizes">
                </div>
            </div>

             <!-- Skill Page Rates (also addressed as SPage) -->  
             <div class="rate-up-sPage">
                <div class="rate-up-text">
                    <p class="left-rate-text"> Rate-UP Skill Page </p>
                    <p class="right-rate-text orange-text"> 0.68% </p>
                </div>
                <img src="{{ url_for('static', filename='images/characters/skill page black asta.png') }}" alt="SPageBlackAsta" class="rate-up-image">
            </div>

            <div class="other-ssr-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SSR </p>
                    <p class="right-rate-text yellow-text"> 0.82% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other ssr skill pages.png') }}" alt="otherSSRPages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-sr-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> SR </p>
                    <p class="right-rate-text blue-text"> 10.00% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other sr skill pages.png') }}" alt="otherSRPages" class="other-rate-sizes">
                </div>
            </div>

            <div class="other-r-sPages">
                <div class="rate-up-text">
                    <p class="left-rate-text"> R </p>
                    <p class="right-rate-text green-text"> 28.50% </p>
                </div>
                <div class="other-rate-images">
                    <img src="{{ url_for('static', filename='images/core/other r skill pages.png') }}" alt="otherRPages" class="other-rate-sizes">
                </div>
            </div>

        </div>

    {% endif %}

{% endblock %}